### ISSUE TITLE
B is not idempotent for identical requests

### ISSUE THREAD

**Issue by civsiv** [openactive/OpenActive.Server.NET#100]
The Booking Specification states the following:
"note call to B is idempotent for the case where OrderItems match".

However this is not the case for two identical B requests. An `OrderAlreadyExistsError` error is returned.

An example of the B request sent is below:

```
{
    "@context": [
        "https://openactive.io/"
    ],
    "broker": {
        "id": "google",
        "name": "Google",
        "type": "Organization"
    },
    "brokerRole": "https://openactive.io/AgentBroker",
    "customer": {
        "email": "test@example.com",
        "familyName": "Doe",
        "givenName": "Jane",
        "id": "0",
        "telephone": "+1 800-789-7890",
        "type": "Person"
    },
    "orderedItem": [
        {
            "acceptedOffer": {
                "id": "https://iminoareferenceimplementation.azurewebsites.net/api/identifiers/session-series/209#/offers/0",
                "type": "Offer"
            },
            "orderedItem": {
                "id": "https://iminoareferenceimplementation.azurewebsites.net/api/identifiers/scheduled-sessions/209/events/2084",
                "type": "ScheduledSession"
            },
            "position": 0,
            "type": "OrderItem"
        }
    ],
    "seller": {
        "id": "https://iminoareferenceimplementation.azurewebsites.net/api/identifiers/sellers/1",
        "type": "Organization"
    },
    "totalPaymentDue": {
        "price": 0,
        "priceCurrency": "GBP",
        "type": "PriceSpecification"
    },
    "type": "Order"
}
```

**Comment by lukehesluke** [comment]
I concur. Here is a test run which tests idempotency (and fails):

[free-opportunities_opportunity-free-without-checkpoints_OpenBookingSimpleFlow_FacilityUseSlot.md](https://github.com/openactive/OpenActive.Server.NET/files/6433457/free-opportunities_opportunity-free-without-checkpoints_OpenBookingSimpleFlow_FacilityUseSlot.md)

This is only for Simple Flow, btw. Approval Flow allows a repeated B:

[free-opportunities_opportunity-free-without-checkpoints_OpenBookingApprovalFlow_FacilityUseSlot.md](https://github.com/openactive/OpenActive.Server.NET/files/6433460/free-opportunities_opportunity-free-without-checkpoints_OpenBookingApprovalFlow_FacilityUseSlot.md)

**Comment by nickevansuk** [comment]
Noting this could be solved by storing the hash  of a successful request at B, along with the successful response, and then reading that hash if an Order already exists to determine whether to return the same response, or an OrderAlreadyExistsError

**Comment by nickevansuk** [comment]
The hash should be computed on the request string before it gets deserialised, and passed into the flowContext.

Either then:
1) An additional idempotency hook then needs to be added to the OrderStore - that attempts to get the response for B from the Orders table if it exists
2) A response is possible from CreateOrder that simply returns the original response based on the hash

**Comment by matdavies** [comment]
I started trying to implement per the above design suggestions, but came across an issue:

`StoreBookingEngine.ProcessFlowRequest` (which is where I think you're suggesting we make modifications) returns `TOrder`, not a string (or `ResponseContent`).  So part 3 above is not really possible in that method?  Instead if `GetOrder` returns false, we'd need to deserialise the response into a TOrder again, and return that?

So instead I looked at modifying `ProcessOrderCreationB` in `CustomBookingEngine`, but of course, `CustomBookingEngine` does not have access to the `OrderStore`, so it can't call the `GetIdempotentOrderResponse` method from there.  Instead `IBookingEngine` would need that `GetIdempotentOrderResponse` method on it (which, in the `StoreBookingEngine`, would just pass off to the `OrderStore`).

Let me know which you would prefer, or if I've got the wrong end of the stick.

Also, the above aside, I think `CreateOrder` should return this:

```c#
    /// <summary>
    /// Result of creating (or attempting to create) an Order in a store
    /// </summary>
    public enum CreateOrderResult
    {
        OrderSuccessfullyCreated,
        OrderAlreadyExists
    }
```

instead of a bool, as the above matches `DeleteOrder` and makes it easier to see what to return (as opposed to having to guess that you need to return false from `CreateOrder` if the order already exists - otherwise people could easily just continue to throw exceptions there which is what the reference impl does)

**Comment by nickevansuk** [comment]
Yes sounds good - `CreateOrderResult` and updating `CustomBookingEngine` as you say.

Can see the advantages of doing this at the `CustomBookingEngine` level, as for one implementation pattern we're really adding a caching hook.

The tradeoff is that this is more prescriptively suggesting that a separate caching layer is used, rather than e.g. using the database to store it within the same transaction. The alternative would be that `ProcessFlowRequest` returns a string, and responsibility of OpenActiveSerializer.Serialize(response) is moved into the StoreBookingEngine?

**Comment by nickevansuk** [comment]
After some thinking about the design, I've opted for doing this optionally at the `CustomBookingEngine` level (see #207), as it's cleaner and more closely follows the pattern of other libraries e.g. https://github.com/ikyriak/IdempotentAPI (which could be used if https://github.com/openactive/open-booking-api/issues/239 is adopted in future).

This does mean that it's not as easy to store a hash of the request in the database within `CreateOrder`, however it does result in a more maintainable solution overall.
